// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: receipts.v1/receipts.proto

package receiptsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	receipts_v1 "github.com/manzanit0/mcduck/api/receipts.v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ReceiptsServiceName is the fully-qualified name of the ReceiptsService service.
	ReceiptsServiceName = "receipts.v1.ReceiptsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ReceiptsServiceCreateReceiptProcedure is the fully-qualified name of the ReceiptsService's
	// CreateReceipt RPC.
	ReceiptsServiceCreateReceiptProcedure = "/receipts.v1.ReceiptsService/CreateReceipt"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	receiptsServiceServiceDescriptor             = receipts_v1.File_receipts_v1_receipts_proto.Services().ByName("ReceiptsService")
	receiptsServiceCreateReceiptMethodDescriptor = receiptsServiceServiceDescriptor.Methods().ByName("CreateReceipt")
)

// ReceiptsServiceClient is a client for the receipts.v1.ReceiptsService service.
type ReceiptsServiceClient interface {
	CreateReceipt(context.Context, *connect.Request[receipts_v1.CreateReceiptRequest]) (*connect.Response[receipts_v1.CreateReceiptResponse], error)
}

// NewReceiptsServiceClient constructs a client for the receipts.v1.ReceiptsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReceiptsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReceiptsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &receiptsServiceClient{
		createReceipt: connect.NewClient[receipts_v1.CreateReceiptRequest, receipts_v1.CreateReceiptResponse](
			httpClient,
			baseURL+ReceiptsServiceCreateReceiptProcedure,
			connect.WithSchema(receiptsServiceCreateReceiptMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// receiptsServiceClient implements ReceiptsServiceClient.
type receiptsServiceClient struct {
	createReceipt *connect.Client[receipts_v1.CreateReceiptRequest, receipts_v1.CreateReceiptResponse]
}

// CreateReceipt calls receipts.v1.ReceiptsService.CreateReceipt.
func (c *receiptsServiceClient) CreateReceipt(ctx context.Context, req *connect.Request[receipts_v1.CreateReceiptRequest]) (*connect.Response[receipts_v1.CreateReceiptResponse], error) {
	return c.createReceipt.CallUnary(ctx, req)
}

// ReceiptsServiceHandler is an implementation of the receipts.v1.ReceiptsService service.
type ReceiptsServiceHandler interface {
	CreateReceipt(context.Context, *connect.Request[receipts_v1.CreateReceiptRequest]) (*connect.Response[receipts_v1.CreateReceiptResponse], error)
}

// NewReceiptsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReceiptsServiceHandler(svc ReceiptsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	receiptsServiceCreateReceiptHandler := connect.NewUnaryHandler(
		ReceiptsServiceCreateReceiptProcedure,
		svc.CreateReceipt,
		connect.WithSchema(receiptsServiceCreateReceiptMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/receipts.v1.ReceiptsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReceiptsServiceCreateReceiptProcedure:
			receiptsServiceCreateReceiptHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReceiptsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReceiptsServiceHandler struct{}

func (UnimplementedReceiptsServiceHandler) CreateReceipt(context.Context, *connect.Request[receipts_v1.CreateReceiptRequest]) (*connect.Response[receipts_v1.CreateReceiptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("receipts.v1.ReceiptsService.CreateReceipt is not implemented"))
}
