// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: receipts.v1/receipts.proto

package receiptsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReceiptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiptFiles [][]byte `protobuf:"bytes,1,rep,name=receipt_files,json=receiptFiles,proto3" json:"receipt_files,omitempty"`
}

func (x *CreateReceiptRequest) Reset() {
	*x = CreateReceiptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_v1_receipts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiptRequest) ProtoMessage() {}

func (x *CreateReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_v1_receipts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiptRequest.ProtoReflect.Descriptor instead.
func (*CreateReceiptRequest) Descriptor() ([]byte, []int) {
	return file_receipts_v1_receipts_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReceiptRequest) GetReceiptFiles() [][]byte {
	if x != nil {
		return x.ReceiptFiles
	}
	return nil
}

type CreateReceiptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiptIds []uint64 `protobuf:"varint,1,rep,packed,name=receipt_ids,json=receiptIds,proto3" json:"receipt_ids,omitempty"`
}

func (x *CreateReceiptResponse) Reset() {
	*x = CreateReceiptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_v1_receipts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiptResponse) ProtoMessage() {}

func (x *CreateReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_v1_receipts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiptResponse.ProtoReflect.Descriptor instead.
func (*CreateReceiptResponse) Descriptor() ([]byte, []int) {
	return file_receipts_v1_receipts_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReceiptResponse) GetReceiptIds() []uint64 {
	if x != nil {
		return x.ReceiptIds
	}
	return nil
}

type UpdateReceiptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vendor        *string                `protobuf:"bytes,2,opt,name=vendor,proto3,oneof" json:"vendor,omitempty"`
	PendingReview *bool                  `protobuf:"varint,3,opt,name=pending_review,json=pendingReview,proto3,oneof" json:"pending_review,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3,oneof" json:"date,omitempty"`
}

func (x *UpdateReceiptRequest) Reset() {
	*x = UpdateReceiptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_v1_receipts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReceiptRequest) ProtoMessage() {}

func (x *UpdateReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_v1_receipts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReceiptRequest.ProtoReflect.Descriptor instead.
func (*UpdateReceiptRequest) Descriptor() ([]byte, []int) {
	return file_receipts_v1_receipts_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateReceiptRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateReceiptRequest) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *UpdateReceiptRequest) GetPendingReview() bool {
	if x != nil && x.PendingReview != nil {
		return *x.PendingReview
	}
	return false
}

func (x *UpdateReceiptRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type UpdateReceiptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReceiptResponse) Reset() {
	*x = UpdateReceiptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_v1_receipts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReceiptResponse) ProtoMessage() {}

func (x *UpdateReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_v1_receipts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReceiptResponse.ProtoReflect.Descriptor instead.
func (*UpdateReceiptResponse) Descriptor() ([]byte, []int) {
	return file_receipts_v1_receipts_proto_rawDescGZIP(), []int{3}
}

type DeleteReceiptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteReceiptRequest) Reset() {
	*x = DeleteReceiptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_v1_receipts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReceiptRequest) ProtoMessage() {}

func (x *DeleteReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_v1_receipts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReceiptRequest.ProtoReflect.Descriptor instead.
func (*DeleteReceiptRequest) Descriptor() ([]byte, []int) {
	return file_receipts_v1_receipts_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReceiptRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteReceiptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReceiptResponse) Reset() {
	*x = DeleteReceiptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receipts_v1_receipts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReceiptResponse) ProtoMessage() {}

func (x *DeleteReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receipts_v1_receipts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReceiptResponse.ProtoReflect.Descriptor instead.
func (*DeleteReceiptResponse) Descriptor() ([]byte, []int) {
	return file_receipts_v1_receipts_proto_rawDescGZIP(), []int{5}
}

var File_receipts_v1_receipts_proto protoreflect.FileDescriptor

var file_receipts_v1_receipts_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2f, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x49, 0x64,
	0x73, 0x22, 0xcb, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x0e, 0x70, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x01, 0x52, 0x0d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x02, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x76, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x22,
	0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x9f, 0x02, 0x0a, 0x0f, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x21,
	0x2e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x21, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x58, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x12, 0x21, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0xa5, 0x01, 0x0a, 0x0f,
	0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x42,
	0x0d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e,
	0x7a, 0x61, 0x6e, 0x69, 0x74, 0x30, 0x2f, 0x6d, 0x63, 0x64, 0x75, 0x63, 0x6b, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x3b, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x52, 0x58, 0x58, 0xaa, 0x02,
	0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0b, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x17, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x70, 0x74, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_receipts_v1_receipts_proto_rawDescOnce sync.Once
	file_receipts_v1_receipts_proto_rawDescData = file_receipts_v1_receipts_proto_rawDesc
)

func file_receipts_v1_receipts_proto_rawDescGZIP() []byte {
	file_receipts_v1_receipts_proto_rawDescOnce.Do(func() {
		file_receipts_v1_receipts_proto_rawDescData = protoimpl.X.CompressGZIP(file_receipts_v1_receipts_proto_rawDescData)
	})
	return file_receipts_v1_receipts_proto_rawDescData
}

var file_receipts_v1_receipts_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_receipts_v1_receipts_proto_goTypes = []any{
	(*CreateReceiptRequest)(nil),  // 0: receipts.v1.CreateReceiptRequest
	(*CreateReceiptResponse)(nil), // 1: receipts.v1.CreateReceiptResponse
	(*UpdateReceiptRequest)(nil),  // 2: receipts.v1.UpdateReceiptRequest
	(*UpdateReceiptResponse)(nil), // 3: receipts.v1.UpdateReceiptResponse
	(*DeleteReceiptRequest)(nil),  // 4: receipts.v1.DeleteReceiptRequest
	(*DeleteReceiptResponse)(nil), // 5: receipts.v1.DeleteReceiptResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_receipts_v1_receipts_proto_depIdxs = []int32{
	6, // 0: receipts.v1.UpdateReceiptRequest.date:type_name -> google.protobuf.Timestamp
	0, // 1: receipts.v1.ReceiptsService.CreateReceipt:input_type -> receipts.v1.CreateReceiptRequest
	2, // 2: receipts.v1.ReceiptsService.UpdateReceipt:input_type -> receipts.v1.UpdateReceiptRequest
	4, // 3: receipts.v1.ReceiptsService.DeleteReceipt:input_type -> receipts.v1.DeleteReceiptRequest
	1, // 4: receipts.v1.ReceiptsService.CreateReceipt:output_type -> receipts.v1.CreateReceiptResponse
	3, // 5: receipts.v1.ReceiptsService.UpdateReceipt:output_type -> receipts.v1.UpdateReceiptResponse
	5, // 6: receipts.v1.ReceiptsService.DeleteReceipt:output_type -> receipts.v1.DeleteReceiptResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_receipts_v1_receipts_proto_init() }
func file_receipts_v1_receipts_proto_init() {
	if File_receipts_v1_receipts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_receipts_v1_receipts_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateReceiptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_v1_receipts_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateReceiptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_v1_receipts_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateReceiptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_v1_receipts_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateReceiptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_v1_receipts_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReceiptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receipts_v1_receipts_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReceiptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_receipts_v1_receipts_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_receipts_v1_receipts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_receipts_v1_receipts_proto_goTypes,
		DependencyIndexes: file_receipts_v1_receipts_proto_depIdxs,
		MessageInfos:      file_receipts_v1_receipts_proto_msgTypes,
	}.Build()
	File_receipts_v1_receipts_proto = out.File
	file_receipts_v1_receipts_proto_rawDesc = nil
	file_receipts_v1_receipts_proto_goTypes = nil
	file_receipts_v1_receipts_proto_depIdxs = nil
}
