[build]
builder = "dockerfile"
dockerfilePath= "Dockerfile"
watchPatterns = [
  "cmd/bot/**",
  "pkg/**", 
  "internal/**", 
  "gen/**",
  "railway/bot.toml", 
  "go.mod", 
  "go.sum",
  "Dockerfile",
]

[deploy]
numReplicas = 1 
healthcheckPath = "/ping"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
