[build]
builder = "dockerfile"
dockerfilePath= "Dockerfile"
watchPatterns = [
    "cmd/dots/**",
    "pkg/**",
    "internal/**",
    "gen/**",
    "railway",
    "go.mod",
    "go.sum",
    "Dockerfile",
]

[deploy]
numReplicas = 1 
healthcheckPath = "/ping"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
