[build]
builder = "nixpacks"
watchPatterns = ["cmd/parser/**", "pkg/**", "internal/**", "railway", "go.mod", "go.sum"]
buildCommand = "go build -o bin/parser ./cmd/parser"

[deploy]
startCommand = "bin/parser"
healthcheckPath = "/ping"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
