[build]
builder = "nixpacks"
watchPatterns = [
  "cmd/parser/**",
  "pkg/**", 
  "internal/**", 
  "gen/**",
  "railway/parser.toml", 
  "go.mod", 
  "go.sum",
]
buildCommand = "go build -o bin/parser ./cmd/parser"

[deploy]
numReplicas = 1 
startCommand = "bin/parser"
healthcheckPath = "/ping"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
