[build]
builder = "nixpacks"
watchPatterns = ["cmd/service/**", "pkg", "railway", "go.mod", "go.sum"]
buildCommand = "go build -o bin/service ./cmd/service"

[deploy]
startCommand = "bin/service"
healthcheckPath = "/ping"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
