[build]
builder = "nixpacks"
watchPatterns = [
    "cmd/api/**",
    "pkg/**",
    "internal/**",
    "railway",
    "go.mod",
    "go.sum",
]
buildCommand = "go build -o bin/api ./cmd/api"

[deploy]
startCommand = "bin/api"
healthcheckPath = "/ping"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
