// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login_index from "./routes/login/index.tsx";
import * as $receipts_id_ from "./routes/receipts/[id].tsx";
import * as $receipts_index from "./routes/receipts/index.tsx";
import * as $signout_index from "./routes/signout/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ExpensesTable from "./islands/ExpensesTable.tsx";
import * as $MobileHeader from "./islands/MobileHeader.tsx";
import * as $ReceiptForm from "./islands/ReceiptForm.tsx";
import * as $ReceiptStatusDropdown from "./islands/ReceiptStatusDropdown.tsx";
import * as $ReceiptsTable from "./islands/ReceiptsTable.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login/index.tsx": $login_index,
    "./routes/receipts/[id].tsx": $receipts_id_,
    "./routes/receipts/index.tsx": $receipts_index,
    "./routes/signout/index.tsx": $signout_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/ExpensesTable.tsx": $ExpensesTable,
    "./islands/MobileHeader.tsx": $MobileHeader,
    "./islands/ReceiptForm.tsx": $ReceiptForm,
    "./islands/ReceiptStatusDropdown.tsx": $ReceiptStatusDropdown,
    "./islands/ReceiptsTable.tsx": $ReceiptsTable,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
